#--------------------------------------------------------------------
### engine ###
#--------------------------------------------------------------------
#' Split Engine: User-Defined
#'
#' Passes through externally provided train/test data without further modification.
#'
#' **Inputs (passed to engine via wrapper):**
#' - `train`: A pre-defined training dataset.
#' - `test`: A pre-defined test dataset.
#'
#' **Output (returned to wrapper):**
#' - A list with `train` and `test` data frames as provided.
#'
#' @param train A pre-defined training dataset.
#' @param test A pre-defined test dataset.
#'
#' @return A list with the train and test sets.
#' @export
engine_split_userdefined <- function(train, test) {
  list(train = train, test = test)
}
#--------------------------------------------------------------------



#--------------------------------------------------------------------
### wrapper ###
#--------------------------------------------------------------------
#' Wrapper for Split Engine: User-Defined
#'
#' Uses pre-specified train/test data from the control object. Intended for externally managed splits.
#' Returns standardized output using `initialize_output_split()`.
#'
#' This wrapper internally sets `internal_skip_validation = TRUE` to bypass structural engine validation.  
#' This is necessary because user-defined splits are not generated by the engine but injected directly via `control$data$train` and `control$data$test`.
#' Validation is therefore not meaningful and intentionally skipped.
#'
#' **Standardized Inputs:**
#' - `control$data$train`: Pre-specified training dataset.
#' - `control$data$test`: Pre-specified test dataset.
#'
#' **Standardized Output (returned to framework):**
#' - A list structured via `initialize_output_split()`:
#'   - `split_type`: "userdefined".
#'   - `splits`: Named list `user` with train/test sets.
#'   - `seed`: `NULL`.
#'   - `params`: `NULL`.
#'   - `specific_output`: `list(source = "user_provided")`.
#'
#' @param control A standardized control object with externally assigned train/test data.
#' @return A standardized splitter output object.
#' @export
wrapper_split_userdefined <- function(control) {
  # Signal to validation system that this wrapper should be skipped
  if (isTRUE(control$internal_skip_validation)) {
    return(list(skip_validation = TRUE))
  }
  
  if (is.null(control$data$train) || is.null(control$data$test)) {
    stop("wrapper_split_userdefined: Both train and test data must be provided in control$data.")
  }
  
  message("[INFO] Using user-provided train/test split.")
  
  # Call dummy engine for completeness
  split <- engine_split_userdefined(train = control$data$train, test = control$data$test)
  
  # Standardized output
  initialize_output_split(
    split_type = "userdefined",
    splits = list(user = split),
    seed = NULL,
    params = NULL,
    specific_output = list(source = "user_provided")
  )
}
#--------------------------------------------------------------------



#--------------------------------------------------------------------
### default params
#--------------------------------------------------------------------
#' Default Parameters for Splitter Engine: User-Defined
#'
#' This engine does not require or support any additional parameters because
#' it operates exclusively on externally provided data (via `control$data$train` and `control$data$test`).
#' It is intended for workflows where splitting happens outside the framework.
#'
#' **Purpose:**
#' - Registers the engine in the global system.
#' - Ensures compatibility with engine registration and validation logic.
#' - Not used during execution.
#'
#' @return `NULL`, as no parameters are needed.
#' @export
default_params_split_userdefined <- function() {
  NULL
}
#--------------------------------------------------------------------