#--------------------------------------------------------------------
### Output Initializer: Reportelement ###
#--------------------------------------------------------------------
#' Output Initializer: Single Reportelement Object
#'
#' Creates a standardized reportelement object for use within full reports or standalone exports.
#' This function ensures uniform structure across all engines generating visual or textual output
#' for downstream reporting or publishing steps.
#'
#' **Purpose:**
#' - Standardizes return values from all reportelement engines.
#' - Enables interoperability with report and publishing engines.
#'
#' **Standardized Output:**
#' - `type`: Type of content, e.g., `"table"`, `"plot"`, `"text"`, `"interactive"`.
#' - `content`: The actual object, such as a `data.frame`, `ggplot`, or character string.
#' - `compatible_formats`: Vector of allowed export formats (e.g., `c("pdf", "html", "xlsx")`).
#' - `input_data`: Optional raw input used by the engine (e.g., `aggregated_results` or `workflow_results`).
#' - `params`: Optional parameters passed to the engine during construction.
#' - `specific_output`: Optional engine-specific diagnostics, annotations, or helper data.
#'
#' **Usage Example (inside a reportelement engine):**
#' ```r
#' initialize_output_reportelement(
#'   type = "table",
#'   content = summary_table,
#'   compatible_formats = c("pdf", "html", "xlsx"),
#'   input_data = aggregated_results,
#'   params = control$params$reportelement$params[["split_table"]],
#'   specific_output = list(row_count = nrow(summary_table))
#' )
#' ```
#'
#' @param type Character. Content type descriptor (e.g., `"plot"`, `"table"`, `"text"`).
#' @param content Any R object. The content generated by the reportelement engine.
#' @param compatible_formats Character vector. Supported export formats.
#' @param input_data Optional. Raw data used to compute this reportelement.
#' @param params Optional. Engine parameters used during generation.
#' @param specific_output Optional. Additional diagnostics or engine-specific metadata.
#'
#' @return A standardized list representing a single reportelement object.
#' @export
initialize_output_reportelement <- function(type, content, compatible_formats, input_data = NULL, params = NULL, specific_output = NULL) {
  # Base fields: Required for all reporting engines
  output <- list(
    type = type,
    content = content,
    compatible_formats = compatible_formats,
    input_data = input_data
  )
  
  # Optional fields
  if (!is.null(params)) {
    output$params <- params
  }
  if (!is.null(specific_output)) {
    output$specific_output <- specific_output
  }
  
  return(output)
}
#--------------------------------------------------------------------