name: R-CMD-check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          devtools::check()
        shell: Rscript {0}
