name: R-CMD-check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  R-CMD-check:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install TinyTeX
        run: |
          Rscript -e 'install.packages("tinytex"); tinytex::install_tinytex(force = TRUE)'

      - name: Verify LaTeX installation
        run: pdflatex --version || echo "pdflatex not found"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools
          needs: devtools
          
      - name: Copy LLM engine files to inst/ for ZIP builder
        run: |
          Rscript tools/dev/copy_engine_build_materials.R
          
      - name: Commit and push engine files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add inst/example_enginebuild_LLM/
          git diff --cached --quiet || git commit -m "Auto-sync LLM example/vignette [skip-ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run R CMD check
        run: |
          devtools::install_deps(dependencies = TRUE)
          devtools::check()
        shell: Rscript {0}
