name: R-CMD-check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install package dependencies
        run: devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run R CMD check
        run: devtools::check()
        shell: Rscript {0}
