name: R-CMD-check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install TinyTeX
        run: |
          Rscript -e 'install.packages("tinytex"); tinytex::install_tinytex(force = TRUE)'
          echo "TinyTeX installed"

      - name: Verify LaTeX installation
        run: pdflatex --version || echo "pdflatex not found"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools
          needs: devtools
          
      - name: Copy LLM engine files to inst/ for ZIP builder
        run: |
          Rscript dev/copy_engine_files.R

      - name: Run R CMD check
        run: |
          devtools::install_deps(dependencies = TRUE)
          devtools::check()
        shell: Rscript {0}
