name: R-CMD-check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y \
          texlive-latex-base texlive-latex-recommended \
          texlive-fonts-recommended texlive-extra-utils \
          texlive-fonts-extra lmodern

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools
          needs: devtools

      - name: Run R CMD check
        run: |
          devtools::install_deps(dependencies = TRUE)
          devtools::check()
        shell: Rscript {0}
